### ISSUE TITLE
Cannot read property 'makeHref' of undefined

### ISSUE THREAD

**Issue by reggi** [choonkending/react-webpack-node#73] opened 2015-09-12 21:29 UTC
When running `npm run devHotLoader` and opening `http://localhost:3000/`.

```
TypeError: Cannot read property 'makeHref' of undefined
    at render (/Users/thomas/Desktop/github-clones/react-webpack-node/node_modules/react-router/lib/Link.js:90:19)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/thomas/Desktop/github-clones/react-webpack-node/node_modules/react/lib/ReactCompositeComponent.js:789:34)
    at ReactCompositeComponentMixin._renderValidatedComponent (/Users/thomas/Desktop/github-clones/react-webpack-node/node_modules/react/lib/ReactCompositeComponent.js:816:14)
    at wrapper [as _renderValidatedComponent] (/Users/thomas/Desktop/github-clones/react-webpack-node/node_modules/react/lib/ReactPerf.js:70:21)
    at ReactCompositeComponentMixin.mountComponent (/Users/thomas/Desktop/github-clones/react-webpack-node/node_modules/react/lib/ReactCompositeComponent.js:237:30)
    at wrapper [as mountComponent] (/Users/thomas/Desktop/github-clones/react-webpack-node/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/thomas/Desktop/github-clones/react-webpack-node/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/thomas/Desktop/github-clones/react-webpack-node/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/thomas/Desktop/github-clones/react-webpack-node/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/thomas/Desktop/github-clones/react-webpack-node/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (/Users/thomas/Desktop/github-clones/react-webpack-node/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactCompositeComponentMixin.mountComponent (/Users/thomas/Desktop/github-clones/react-webpack-node/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at wrapper [as mountComponent] (/Users/thomas/Desktop/github-clones/react-webpack-node/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/thomas/Desktop/github-clones/react-webpack-node/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactCompositeComponentMixin.mountComponent (/Users/thomas/Desktop/github-clones/react-webpack-node/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at wrapper [as mountComponent] (/Users/thomas/Desktop/github-clones/react-webpack-node/node_modules/react/lib/ReactPerf.js:70:21)
```

**Comment by jure** [comment] 2015-09-15 09:22
This is a duplicate of #64, not sure if there is a general solution yet, but you can always try running it without the hot loader.

**Comment by choonkending** [comment] 2015-12-05 05:44
@reggi if you run `npm run dev` now, it should work. Pull the latest master. :)

**Closed** 2015-12-06 03:12 UTC
