### ISSUE TITLE
TypeError: Cannot read property 'makeHref' of undefined

### ISSUE THREAD

**Issue by rhys-edwards** [choonkending/react-webpack-node#64] opened 2015-08-31 06:24 UTC
Still having issues getting this set up locally. 
Have looked towards this but can't see the router being called twice in any components;
https://github.com/rackt/react-router/issues/1595

Thoughts?

````
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (router) while mounting Link (see: http://fb.me/react-context-by-parent)
TypeError: Cannot read property 'makeHref' of undefined
    at render (/Users/rhysedwards/Downloads/ideas/node_modules/react-router/lib/Link.js:90:19)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/rhysedwards/Downloads/ideas/node_modules/react/lib/ReactCompositeComponent.js:789:34)
    at ReactCompositeComponentMixin._renderValidatedComponent (/Users/rhysedwards/Downloads/ideas/node_modules/react/lib/ReactCompositeComponent.js:816:14)
    at wrapper [as _renderValidatedComponent] (/Users/rhysedwards/Downloads/ideas/node_modules/react/lib/ReactPerf.js:70:21)
    at ReactCompositeComponentMixin.mountComponent (/Users/rhysedwards/Downloads/ideas/node_modules/react/lib/ReactCompositeComponent.js:237:30)
    at wrapper [as mountComponent] (/Users/rhysedwards/Downloads/ideas/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/rhysedwards/Downloads/ideas/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/rhysedwards/Downloads/ideas/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/rhysedwards/Downloads/ideas/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/rhysedwards/Downloads/ideas/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (/Users/rhysedwards/Downloads/ideas/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactCompositeComponentMixin.mountComponent (/Users/rhysedwards/Downloads/ideas/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at wrapper [as mountComponent] (/Users/rhysedwards/Downloads/ideas/node_modules/react/lib/ReactPerf.js:70:21)
    at Object.ReactReconciler.mountComponent (/Users/rhysedwards/Downloads/ideas/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactCompositeComponentMixin.mountComponent (/Users/rhysedwards/Downloads/ideas/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at wrapper [as mountComponent] (/Users/rhysedwards/Downloads/ideas/node_modules/react/lib/ReactPerf.js:70:21)
Error: Invariant Violation: Server-side <Router>s need location, branch, params, and components props. Try using Router.run to get all the props you need
    at invariant (/Users/rhysedwards/Downloads/ideas/node_modules/react-router/node_modules/invariant/invariant.js:44:15)
    at componentWillMount (/Users/rhysedwards/Downloads/ideas/node_modules/react-router/lib/Router.js:254:34)
    at ReactCompositeComponentMixin.mountComponent (/Users/rhysedwards/Downloads/ideas/node_modules/react/lib/ReactCompositeComponent.js:228:14)
    at wrapper [as mountComponent] (/Users/rhysedwards/Downloads/ideas/node_modules/react/lib/ReactPerf.js:70:21)
    at /Users/rhysedwards/Downloads/ideas/node_modules/react/lib/ReactServerRendering.js:42:27
    at ReactServerRenderingTransaction.Mixin.perform (/Users/rhysedwards/Downloads/ideas/node_modules/react/lib/Transaction.js:134:20)
    at Object.renderToString (/Users/rhysedwards/Downloads/ideas/node_modules/react/lib/ReactServerRendering.js:39:24)
    at /Users/rhysedwards/Downloads/ideas/public/assets/app.server.js:101:39
    at /Users/rhysedwards/Downloads/ideas/node_modules/react-router/lib/Router.js:53:7
    at done (/Users/rhysedwards/Downloads/ideas/node_modules/react-router/lib/AsyncUtils.js:14:14)
    at next (/Users/rhysedwards/Downloads/ideas/node_modules/react-router/lib/AsyncUtils.js:24:12)
    at /Users/rhysedwards/Downloads/ideas/node_modules/react-router/lib/RoutingUtils.js:120:9
    at /Users/rhysedwards/Downloads/ideas/node_modules/react-router/lib/RoutingUtils.js:100:13
    at done (/Users/rhysedwards/Downloads/ideas/node_modules/react-router/lib/AsyncUtils.js:14:14)
    at next (/Users/rhysedwards/Downloads/ideas/node_modules/react-router/lib/AsyncUtils.js:24:12)
    at /Users/rhysedwards/Downloads/ideas/node_modules/react-router/lib/RoutingUtils.js:120:9

````

**Comment by choonkending** [comment] 2015-09-01 02:26
@rhys-edwards Do you have a branch we could take a look at?

Also, try `npm install` again to make sure we've got the latest react-router. I had this problem before, but I fixed it with the new webpack.config.

**Comment by rhys-edwards** [comment] 2015-09-01 02:36
@choonkending no branches to speak of as it was a clean clone. Can re-up it for you to take a look like if you wish?

Gave `npm install` a go but still being thrown the same error.

**Comment by choonkending** [comment] 2015-09-01 08:14
@rhys-edwards Sure! Would be helpful. I will try to reproduce this error if possible.

**Comment by rhys-edwards** [comment] 2015-09-02 00:31
@choonkending Something going wrong and I can't make a branch due to an auth issue with Github.

In the meantime, I've done a clean clone from the repo; seems like reactt-router has updated with the below.

https://github.com/rackt/react-router/issues/1789

This is now throwing an error:

````
Rhyss-MacBook-Pro:react-webpack-node rhysedwards$ npm run dev

> react-webpack-node@1.2.0 dev /Users/rhysedwards/Desktop/react-webpack-node
> NODE_ENV=development node server/index.js

Environment: development
/Users/rhysedwards/Desktop/react-webpack-node/public/assets/app.server.js:71
 \"react-router/lib/Location\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
                                                                     ^
Error: Cannot find module "react-router/lib/Location"
    at webpackMissingModule (/Users/rhysedwards/Desktop/react-webpack-node/public/assets/app.server.js:71:96)
    at Object.<anonymous> (/Users/rhysedwards/Desktop/react-webpack-node/public/assets/app.server.js:71:198)
    at Object.<anonymous> (/Users/rhysedwards/Desktop/react-webpack-node/public/assets/app.server.js:122:28)
    at __webpack_require__ (/Users/rhysedwards/Desktop/react-webpack-node/public/assets/app.server.js:21:30)
    at /Users/rhysedwards/Desktop/react-webpack-node/public/assets/app.server.js:41:18
    at Object.<anonymous> (/Users/rhysedwards/Desktop/react-webpack-node/public/assets/app.server.js:44:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/rhysedwards/Desktop/react-webpack-node/server/config/routes.js:11:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.2
npm ERR! code ELIFECYCLE
npm ERR! react-webpack-node@1.2.0 dev: `NODE_ENV=development node server/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-webpack-node@1.2.0 dev script 'NODE_ENV=development node server/index.js'.
npm ERR! This is most likely a problem with the react-webpack-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development node server/index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-webpack-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rhysedwards/Desktop/react-webpack-node/npm-debug.log
````

**Comment by davidlygagnon** [comment] 2015-09-02 05:47
I'm also getting the same error on npm run dev.

**Comment by choonkending** [comment] 2015-09-02 09:45
@rhys-edwards @davidlygagnon  Thanks for letting me know. Yea since react-router is still in it's beta stages, there might be many changes. I'll try to get a working version up and running for you guys.

**Comment by jure** [comment] 2015-09-11 10:13
Just another data point I have the same issue here.

**Comment by haganbt** [comment] 2015-09-11 14:09
+1

**Comment by choonkending** [comment] 2015-09-11 14:55
I had this issue as well when react-router beta 4 was released. A temporary fix was to fix it to the beta 3 version https://github.com/choonkending/react-webpack-node/commit/4796bec1dcdd401c56b20213cc435f9d47a32ae7, until beta4 is sorted :)

Let me know if this does not fix it for you (remember to pull the latest version)

**Comment by jure** [comment] 2015-09-15 09:21
Just letting you know, @choonkending, that on a fresh clone, running devHotLoader still produces the above error.

**Comment by choonkending** [comment] 2015-12-06 03:11
@rhys-edwards @jure Sorry it took so long to respond. It shouldn't be an issue with the latest master branch now. 

You should now be able to run `npm run build` once. And from there run `npm run dev` which will start the server + use react-transform-hmr for hot reloading.

Closing this issue but feel free to open a new issue if you find any bugs. Thanks guys!

**Closed by choonkending** 2015-12-06 03:11 UTC
